- name: get hdfs ha state
  tags: test
  command: sudo -Hu hdfs hdfs haadmin -getServiceState {{ ansible_hostname }}
  register: ha_state
  when: groups['namenodes']|count > 1

- name: shutdown active name service
  tags: test
  shell: service hadoop-hdfs-namenode stop; sleep 1
  when: groups['namenodes']|count > 1 and ha_state is defined and ha_state.stdout.find('active') != -1

- name: test hdfs
  tags: test
  command: sudo -Hu hdfs hdfs dfs {{ item }} /ansible_hdfs_test
  with_items:
    - -touchz
    - -rm
  run_once: true

- name: start services
  tags: test
  service: name=hadoop-hdfs-namenode state=started enabled=yes
  when: groups['namenodes']|count > 1 and ha_state is defined and ha_state.stdout.find('active') != -1
